CREATE DATABASE IF NOT EXISTS `php-light`;

USE `php-light`;

CREATE TABLE IF NOT EXISTS `php-light`.`user` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL DEFAULT '',
  `email` VARCHAR(50) NOT NULL DEFAULT '',
  `avatar` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
)ENGINE = InnoDB;

ALTER TABLE `php-light`.`user` ADD COLUMN `profile` VARCHAR(255) NOT NULL DEFAULT '' AFTER `avatar`;
